
services:
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - './docker-compose-pg-init.sh:/docker-entrypoint-initdb.d/init-db.sh'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ecomm -U pgadmin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  sonarqube:
    image: 'sonarqube:26.7.0.124771-community'
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - ${SONAR_PORT:-9000}:9000
    volumes:
      - './docker-compose-sonar-init.sh:/init.sh'
    healthcheck:
      test: [ "CMD-SHELL", "http://localhost:9000/api/system/status" ]
      interval: 5s
      timeout: 5s
      retries: 5

  sonarqube-init:
    image: 'dwdraju/alpine-curl-jq'
    container_name: alpine-curl-jq
    restart: none
    depends_on:
      - sonarqube
    environment:
      SONAR_USER: admin
      SONAR_PASSWORD: admin
      SONAR_NEW_PWD: Admin123456!
    volumes:
      - './docker-compose-sonar-init.sh:/init.sh'
    command: ["/init.sh"]
