
services:
  postgres:
    image: 'postgres:14.4'
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_DB: ${DB_NAME:-postgres}
    ports:
      - ${DB_PORT:-5432}:5432
    volumes:
      - './docker-compose-pg-init.sh:/docker-entrypoint-initdb.d/init-db.sh'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ecomm -U pgadmin" ]
      interval: 5s
      timeout: 5s
      retries: 5

  localstack:
    image: 'localstack/localstack:4.3.0'
    container_name: localstack
    restart: unless-stopped
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
      - IMAGE_NAME=localstack/localstack:4.3.0
    healthcheck:
      test: >-
        curl -sf localhost:4566/_localstack/init/ready | grep -q '"completed": true,'
      interval: 10s
      timeout: 10s
      retries: 3
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  localstack-resources:
    image: 'amazon/aws-cli'
    container_name: localstack-resources
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    volumes:
      - ./:/mnt
    depends_on:
      - localstack
    working_dir: /mnt
    entrypoint: ["/mnt/wait-for-it.sh", "localstack:5432", "-t", "10", "--", "/mnt/docker-compose-localstack-init.sh" ] 

  sonarqube:
    image: 'sonarqube:26.7.0.124771-community'
    container_name: sonarqube
    restart: unless-stopped
    ports:
      - ${SONAR_PORT:-9000}:9000
    volumes:
      - './docker-compose-sonar-init.sh:/init.sh'
    healthcheck:
      test: [ "CMD-SHELL", "http://localhost:9000/api/system/status" ]
      interval: 5s
      timeout: 5s
      retries: 5

  sonarqube-init:
    image: 'dwdraju/alpine-curl-jq'
    container_name: alpine-curl-jq
    restart: none
    depends_on:
      - sonarqube
    environment:
      SONAR_USER: admin
      SONAR_PASSWORD: admin
      SONAR_NEW_PWD: Admin123456!
    volumes:
      - './docker-compose-sonar-init.sh:/init.sh'
    command: ["/init.sh"]
